apiVersion: telemetry.kyma-project.io/v1alpha1
kind: MetricPipeline
metadata:
  name: aws-cloudwatch
spec:
  output:
    otlp:
      endpoint:
        value: http://otel-collector.${KYMA_NS}.svc.cluster.local:4317
